FROM debian:jessie
RUN apt-get update && apt-get install sqlite3 libsqlite3-0

RUN mkdir -p /webapp/
ADD ./db/sqlite /webapp/db/sqlite
ADD ./conf /webapp/conf
ADD ./static /webapp/static
ADD ./views /webapp/views

ADD ./webapp-app /webapp/webapp-app

WORKDIR /webapp
ENTRYPOINT ["./webapp-app"]
