version: '2'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./conf/app.conf:/wepapp/conf/app.conf

    restart: always
    environment:
      BEEGO_RUNMODE: "local-dev"
